name: Greeting on a variable day

on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday ## Environment variable for the entire workflow

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello ## Environment variable for the job
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona ## Environment variable only for the step "Say Hello Mona it's Monday" of the job "greeting_job"

  create_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Push a file to our repository
        run: |
          pwd
          ls -a 
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" 
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          pytest >> log_pytest.txt
          ls -a
          git add .
          git commit -m "random file from action"
          git push
